### ISSUE TITLE
Dataloading Issue

### ISSUE THREAD

**Issue by Aliktk** [RishalAggarwal/3D-Convnet-for-Alzheimer-s-Detection#2]
Hello dear Rishal
your project is awesome but how you load the data into your memory ?

I mean to say for processing these MR images you have to load them by using a data loader and than prepare their dimension for feeding into your neural network. 
You just simply visualze and than nothing in skull stripting to load those skull stripted images? 
please explain

**Comment by RishalAggarwal** [comment]
For training the resnet, I just saved the images as numpy files (np.save) and then read them in again (np.load) for training.
